---
version: 0.2

phases:
  pre_build:
    commands:
      - echo "Install Packer 1.2.1"
      - curl -qL -o packer.zip "https://releases.hashicorp.com/packer/1.2.1/packer_1.2.1_linux_amd64.zip" && unzip packer.zip
      - echo 'Install Ansible'
      - apt-get update -y
      - apt-get install -y software-properties-common
      - apt-add-repository ppa:ansible/ansible
      - apt-get update -y
      - apt-get install -y ansible
  build:
    commands:
      - echo 'Build AMI'
      - ./packer build amazon-linux-2_packer-template.json
  post_build:
    commands:
      - echo "Build finished `date`"